package tools

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/telemetryos/tos-tag/core/approvals"
	"github.com/telemetryos/tos-tag/core/audit"
	"github.com/telemetryos/tos-tag/core/jobs"
	"github.com/telemetryos/tos-tag/core/triggers"
	"github.com/telemetryos/tos-tag/types"
)

type JobScope struct {
	OrganizationID string
	WorkspaceID    string
	ChannelID      string
	ThreadTS       string
	JobID          string
	AttemptID      string
	LeaseToken     string
	SteeringEpoch  int64
	ExpiresAt      time.Time
	AllowedTools   []string
}

type Access struct {
	Endpoint        string
	TriggerEndpoint string
	Capability      string
}

type Bridge struct {
	gateway             Gateway
	jobs                jobs.Queue
	approvals           approvals.Repository
	audit               audit.Appender
	approvalCoordinator interface {
		SuspendAndNotify(context.Context, approvals.RequestScope, approvals.Approval) error
	}
	triggers triggers.Repository

	mu        sync.RWMutex
	scopes    map[string]JobScope
	artifacts map[string][]types.SlackFileUpload
	listener  net.Listener
	server    *http.Server
}

func (b *Bridge) SetTriggerRepository(repository triggers.Repository) { b.triggers = repository }

func (b *Bridge) ImportEnvironmentBindings(ctx context.Context, organizationID string, toolIDs []string) error {
	bindings, err := ImportEnvironmentBindings(ctx, b.gateway.Registry, toolIDs, b.gateway.Secrets, organizationID, nil)
	if err != nil {
		return err
	}
	b.gateway.Bindings = bindings
	return nil
}

func NewBridge(gateway Gateway, queue jobs.Queue, approvalStore approvals.Repository, auditAppender audit.Appender, coordinators ...interface {
	SuspendAndNotify(context.Context, approvals.RequestScope, approvals.Approval) error
}) (*Bridge, error) {
	if queue == nil || approvalStore == nil || auditAppender == nil {
		return nil, errors.New("tool bridge requires jobs, approvals, and audit")
	}
	marketplaceConfigured := gateway.Registry != nil || gateway.Secrets != nil || gateway.Executor.Enabled
	if marketplaceConfigured && (gateway.Registry == nil || gateway.Secrets == nil || !gateway.Executor.Enabled) {
		return nil, errors.New("marketplace tool gateway configuration is incomplete")
	}
	bridge := &Bridge{gateway: gateway, jobs: queue, approvals: approvalStore, audit: auditAppender, scopes: make(map[string]JobScope), artifacts: make(map[string][]types.SlackFileUpload)}
	if len(coordinators) > 0 {
		bridge.approvalCoordinator = coordinators[0]
	}
	return bridge, nil
}

func (b *Bridge) Start() error {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.listener != nil {
		return nil
	}
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return err
	}
	b.listener = listener
	b.server = &http.Server{Handler: http.HandlerFunc(b.serve), ReadHeaderTimeout: 5 * time.Second}
	go func() { _ = b.server.Serve(listener) }()
	return nil
}

func (b *Bridge) Stop(ctx context.Context) error {
	b.mu.Lock()
	server := b.server
	b.server, b.listener = nil, nil
	b.scopes = make(map[string]JobScope)
	b.artifacts = make(map[string][]types.SlackFileUpload)
	b.mu.Unlock()
	if server == nil {
		return nil
	}
	return server.Shutdown(ctx)
}

func (b *Bridge) Register(scope JobScope) (Access, error) {
	if scope.OrganizationID == "" || scope.JobID == "" || scope.AttemptID == "" || scope.LeaseToken == "" || scope.SteeringEpoch <= 0 || !scope.ExpiresAt.After(time.Now().UTC()) {
		return Access{}, errors.New("invalid tool scope")
	}
	capability, err := randomCapability()
	if err != nil {
		return Access{}, err
	}
	b.mu.Lock()
	if b.listener == nil {
		b.mu.Unlock()
		return Access{}, errors.New("tool bridge is not started")
	}
	baseURL := "http://" + b.listener.Addr().String()
	b.scopes[capability] = scope
	b.mu.Unlock()
	return Access{Endpoint: baseURL + "/execute", TriggerEndpoint: baseURL + "/trigger-subscriptions", Capability: capability}, nil
}

func (b *Bridge) RevokeAttempt(_ context.Context, attemptID string) error {
	b.mu.Lock()
	for capability, scope := range b.scopes {
		if scope.AttemptID == attemptID {
			delete(b.scopes, capability)
		}
	}
	delete(b.artifacts, attemptID)
	b.mu.Unlock()
	return nil
}

// TakeArtifacts transfers generated bytes from the reviewed tool gateway to
// the owning in-process worker attempt. They are never serialized to the model.
func (b *Bridge) TakeArtifacts(attemptID string) []types.SlackFileUpload {
	b.mu.Lock()
	defer b.mu.Unlock()
	values := append([]types.SlackFileUpload(nil), b.artifacts[attemptID]...)
	delete(b.artifacts, attemptID)
	return values
}

type bridgeRequest struct {
	ToolID      string      `json:"tool_id"`
	OperationID string      `json:"operation_id"`
	Arguments   []string    `json:"arguments"`
	ApprovalID  string      `json:"approval_id"`
	Wiki        *wikiAction `json:"wiki,omitempty"`
}

// wikiAction is the typed semantic request retained beside the exact reviewed
// argv. It makes an approved delete resumable without giving the worker an
// arbitrary argument surface.
type wikiAction struct {
	Operation     string   `json:"operation"`
	PageReference string   `json:"page_reference,omitempty"`
	Namespace     string   `json:"namespace,omitempty"`
	Query         string   `json:"query,omitempty"`
	Title         string   `json:"title,omitempty"`
	Body          string   `json:"body,omitempty"`
	Tags          []string `json:"tags,omitempty"`
	Note          string   `json:"note,omitempty"`
	Prefix        string   `json:"prefix,omitempty"`
	Tag           string   `json:"tag,omitempty"`
	Format        string   `json:"format,omitempty"`
	Revision      int      `json:"revision,omitempty"`
	Limit         int      `json:"limit,omitempty"`
	Depth         int      `json:"depth,omitempty"`
	AllowEmpty    bool     `json:"allow_empty,omitempty"`
}

func (b *Bridge) serve(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/trigger-subscriptions" {
		b.serveTriggerSubscriptions(w, r)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	if r.Method != http.MethodPost {
		writeBridge(w, http.StatusMethodNotAllowed, map[string]any{"error": "method_not_allowed"})
		return
	}
	if b.gateway.Registry == nil || b.gateway.Secrets == nil || !b.gateway.Executor.Enabled {
		writeBridge(w, http.StatusNotFound, map[string]any{"error": "marketplace_tools_disabled"})
		return
	}
	capability := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	b.mu.RLock()
	scope, ok := b.scopes[capability]
	b.mu.RUnlock()
	if !ok || capability == "" {
		writeBridge(w, http.StatusUnauthorized, map[string]any{"error": "capability_invalid"})
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	var input bridgeRequest
	if err := decoder.Decode(&input); err != nil || input.ToolID == "" || input.OperationID == "" {
		writeBridge(w, http.StatusBadRequest, map[string]any{"error": "invalid_request"})
		return
	}
	if (input.ToolID == "telemetryos.wiki") != (input.Wiki != nil) {
		writeBridge(w, http.StatusBadRequest, map[string]any{"error": "typed_wiki_request_required"})
		return
	}
	if err := b.authorize(r.Context(), scope); err != nil {
		_ = b.RevokeAttempt(r.Context(), scope.AttemptID)
		writeBridge(w, http.StatusForbidden, map[string]any{"error": "execution_revoked"})
		return
	}
	bundle, found := b.gateway.Registry.Resolve(input.ToolID)
	operation, operationFound := findOperation(bundle.Manifest, input.OperationID)
	if !found || !operationFound {
		writeBridge(w, http.StatusNotFound, map[string]any{"error": "operation_not_found"})
		return
	}
	if !containsTool(scope.AllowedTools, input.ToolID) {
		writeBridge(w, http.StatusForbidden, map[string]any{"error": "tool_not_admitted"})
		return
	}
	if input.ToolID == "media.curds" {
		job, err := b.jobs.Get(r.Context(), jobsID(scope.JobID))
		if err != nil {
			writeBridge(w, http.StatusForbidden, map[string]any{"error": "execution_revoked"})
			return
		}
		var intent struct {
			ImageGenerationRequested bool `json:"image_generation_requested"`
		}
		if json.Unmarshal([]byte(job.Input), &intent) != nil || !intent.ImageGenerationRequested {
			writeBridge(w, http.StatusForbidden, map[string]any{"error": "explicit_image_generation_request_required"})
			return
		}
	}
	actionArguments := map[string]any{"argv": input.Arguments}
	if input.Wiki != nil {
		actionArguments["wiki"] = *input.Wiki
	}
	action := approvals.Action{OrganizationID: scope.OrganizationID, JobID: scope.JobID, WorkspaceID: scope.WorkspaceID, ChannelID: scope.ChannelID, ThreadTS: scope.ThreadTS, ToolID: bundle.Manifest.ID, ToolVersion: bundle.Manifest.Version, OperationID: operation.ID, Arguments: actionArguments, Destination: scope.WorkspaceID + "/" + scope.ChannelID, Risk: operation.Risk}
	if operation.RequiresApproval() {
		if input.ApprovalID == "" {
			requesterID := b.approvalRequester(r.Context(), scope)
			approval, err := b.approvals.RequestContext(r.Context(), action, requesterID, approvalTTL(scope))
			if err != nil {
				writeBridge(w, http.StatusInternalServerError, map[string]any{"error": "approval_unavailable"})
				return
			}
			actionBytes, _ := json.Marshal(action)
			if _, err := b.audit.Append(r.Context(), audit.AppendRequest{OrganizationID: scope.OrganizationID, Type: "tool.approval.requested", ActorID: requesterID, ResourceID: approval.ID, RetentionEpoch: time.Now().UTC().Format("2006-01"), IdempotencyKey: "tool-approval/" + approval.ID, Metadata: map[string]any{"tool_id": input.ToolID, "operation_id": input.OperationID, "risk": operation.Risk}, Content: actionBytes}); err != nil {
				writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "audit_unavailable"})
				return
			}
			if b.approvalCoordinator != nil {
				if err := b.approvalCoordinator.SuspendAndNotify(r.Context(), approvals.RequestScope{JobID: jobsID(scope.JobID), LeaseToken: scope.LeaseToken, WorkspaceID: scope.WorkspaceID, ChannelID: scope.ChannelID, ThreadTS: scope.ThreadTS}, approval); err != nil {
					writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "approval_delivery_unavailable"})
					return
				}
			}
			writeBridge(w, http.StatusConflict, map[string]any{"error": "approval_required", "approval_id": approval.ID, "expires_at": approval.ExpiresAt})
			return
		}
		if _, err := b.approvals.ConsumeContext(r.Context(), scope.OrganizationID, input.ApprovalID, action); err != nil {
			writeBridge(w, http.StatusForbidden, map[string]any{"error": "approval_invalid"})
			return
		}
	}
	actionBytes, _ := json.Marshal(action)
	executionID := types.NewID("toolrun")
	if _, err := b.audit.Append(r.Context(), audit.AppendRequest{OrganizationID: scope.OrganizationID, Type: "tool.execution.requested", ActorID: "agent:" + scope.JobID, ResourceID: executionID, RetentionEpoch: time.Now().UTC().Format("2006-01"), IdempotencyKey: "tool-execution/" + executionID + "/requested", Metadata: map[string]any{"tool_id": input.ToolID, "operation_id": input.OperationID, "risk": operation.Risk, "approval_policy": effectiveApprovalPolicy(operation)}, Content: actionBytes}); err != nil {
		writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "audit_unavailable"})
		return
	}
	result, err := b.gateway.Execute(r.Context(), input.ToolID, GatewayRequest{Request: Request{OrganizationID: scope.OrganizationID, JobID: scope.JobID, OperationID: input.OperationID, Args: input.Arguments, Capability: Capability{ToolID: bundle.Manifest.ID, ToolVersion: bundle.Manifest.Version, OperationID: input.OperationID, AttemptToken: scope.AttemptID, SteeringEpoch: scope.SteeringEpoch, ExpiresAt: minTime(scope.ExpiresAt, time.Now().UTC().Add(time.Duration(operation.TimeoutSeconds)*time.Second))}}})
	if err != nil {
		metadata := map[string]any{"tool_id": input.ToolID, "operation_id": input.OperationID, "exit_code": result.ExitCode, "duration_ms": result.Duration.Milliseconds(), "error_code": toolExecutionErrorCode(err)}
		validationCode := toolValidationCode(input.ToolID, result.Output)
		if validationCode != "" {
			metadata["validation_code"] = validationCode
		}
		if _, appendErr := b.audit.Append(r.Context(), audit.AppendRequest{OrganizationID: scope.OrganizationID, Type: "tool.execution.failed", ActorID: "agent:" + scope.JobID, ResourceID: executionID, RetentionEpoch: time.Now().UTC().Format("2006-01"), IdempotencyKey: "tool-execution/" + executionID + "/failed", Metadata: metadata}); appendErr != nil {
			writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "audit_unavailable"})
			return
		}
		response := map[string]any{"error": "tool_failed", "detail": err.Error(), "error_code": metadata["error_code"], "exit_code": result.ExitCode}
		if validationCode != "" {
			response["validation_code"] = validationCode
		}
		// Executor output is already bounded and has declared secret values
		// redacted. Returning it on failure lets the worker correct invalid typed
		// arguments instead of blindly retrying until the callback deadline.
		if result.Output != "" {
			response["output"] = result.Output
		}
		writeBridge(w, http.StatusUnprocessableEntity, response)
		return
	}
	completedMetadata := map[string]any{"tool_id": input.ToolID, "operation_id": input.OperationID, "exit_code": result.ExitCode}
	if result.Artifact != nil {
		completedMetadata["artifact_media_type"] = result.Artifact.MediaType
		completedMetadata["artifact_size"] = result.Artifact.Size
		completedMetadata["artifact_digest"] = result.Artifact.Digest
	}
	if _, err := b.audit.Append(r.Context(), audit.AppendRequest{OrganizationID: scope.OrganizationID, Type: "tool.execution.completed", ActorID: "agent:" + scope.JobID, ResourceID: executionID, RetentionEpoch: time.Now().UTC().Format("2006-01"), IdempotencyKey: "tool-execution/" + executionID + "/completed", Metadata: completedMetadata}); err != nil {
		writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "audit_unavailable"})
		return
	}
	if result.Artifact != nil {
		b.mu.Lock()
		b.artifacts[scope.AttemptID] = append(b.artifacts[scope.AttemptID], types.SlackFileUpload{Name: result.Artifact.Name, Title: result.Artifact.Title, MediaType: result.Artifact.MediaType, Data: append([]byte(nil), result.Artifact.Data...)})
		b.mu.Unlock()
	}
	writeBridge(w, http.StatusOK, result)
}

func toolValidationCode(toolID, output string) string {
	if toolID != "telemetryos.wiki" {
		return ""
	}
	normalized := strings.ToLower(output)
	switch {
	case strings.Contains(normalized, "requires a value"):
		return "wiki.cli.missing_flag_value"
	case strings.Contains(normalized, "unknown flag") || strings.Contains(normalized, "unknown option"):
		return "wiki.cli.unknown_flag"
	case strings.Contains(normalized, "unexpected argument") || strings.Contains(normalized, "unexpected extra"):
		return "wiki.cli.unexpected_argument"
	case strings.Contains(normalized, "requires --title"):
		return "wiki.cli.missing_title"
	case strings.Contains(normalized, "requires inline --body") || strings.Contains(normalized, "requires --body"):
		return "wiki.cli.missing_body"
	case strings.Contains(normalized, "body is empty") || strings.Contains(normalized, "body is whitespace"):
		return "wiki.cli.empty_body"
	case strings.Contains(normalized, "not permitted by") || strings.Contains(normalized, "operation denied"):
		return "wiki.cli.operation_denied"
	case strings.Contains(normalized, "page reference") || strings.Contains(normalized, "invalid page ref"):
		return "wiki.cli.page_reference_invalid"
	case strings.Contains(normalized, "usage:"):
		return "wiki.cli.usage"
	default:
		return ""
	}
}

func toolExecutionErrorCode(err error) string {
	if err == nil {
		return "none"
	}
	switch {
	case errors.Is(err, context.Canceled):
		return "canceled"
	case errors.Is(err, context.DeadlineExceeded):
		return "deadline_exceeded"
	case strings.Contains(err.Error(), "exit code"):
		return "nonzero_exit"
	case strings.Contains(err.Error(), "output exceeded"):
		return "output_limit"
	case strings.Contains(err.Error(), "environment binding"):
		return "binding_unavailable"
	case strings.Contains(err.Error(), "capability"):
		return "capability_invalid"
	case strings.Contains(err.Error(), "script hash changed"):
		return "bundle_changed"
	default:
		return "execution_failed"
	}
}

func effectiveApprovalPolicy(operation Operation) string {
	if operation.Approval != "" {
		return operation.Approval
	}
	return "risk_based"
}

type triggerSubscriptionRequest struct {
	Operation       string  `json:"operation"`
	ID              string  `json:"id,omitempty"`
	Instruction     string  `json:"instruction,omitempty"`
	Cron            string  `json:"cron,omitempty"`
	Timezone        string  `json:"timezone,omitempty"`
	IntervalSeconds int64   `json:"interval_seconds,omitempty"`
	NextRun         string  `json:"next_run,omitempty"`
	MinConfidence   float64 `json:"min_confidence,omitempty"`
	Enabled         *bool   `json:"enabled,omitempty"`
	RootThreadTS    string  `json:"root_thread_ts,omitempty"`
	ApprovalID      string  `json:"approval_id,omitempty"`
}

func (b *Bridge) serveTriggerSubscriptions(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	if r.Method != http.MethodPost {
		writeBridge(w, http.StatusMethodNotAllowed, map[string]any{"error": "method_not_allowed"})
		return
	}
	if b.triggers == nil {
		writeBridge(w, http.StatusNotFound, map[string]any{"error": "trigger_subscriptions_disabled"})
		return
	}
	capability := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	b.mu.RLock()
	scope, ok := b.scopes[capability]
	b.mu.RUnlock()
	if !ok || capability == "" {
		writeBridge(w, http.StatusUnauthorized, map[string]any{"error": "capability_invalid"})
		return
	}
	if err := b.authorize(r.Context(), scope); err != nil {
		_ = b.RevokeAttempt(r.Context(), scope.AttemptID)
		writeBridge(w, http.StatusForbidden, map[string]any{"error": "execution_revoked"})
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, 64<<10)
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	var input triggerSubscriptionRequest
	if err := decoder.Decode(&input); err != nil {
		writeBridge(w, http.StatusBadRequest, map[string]any{"error": "invalid_request"})
		return
	}
	switch input.Operation {
	case "list":
		values, err := b.triggers.ListChannel(r.Context(), scope.OrganizationID, scope.WorkspaceID, scope.ChannelID)
		if err != nil {
			writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "query_failed"})
			return
		}
		writeBridge(w, http.StatusOK, map[string]any{"subscriptions": values})
		return
	case "get":
		value, err := b.triggers.GetContext(r.Context(), scope.OrganizationID, scope.WorkspaceID, scope.ChannelID, input.ID)
		if err != nil {
			writeBridge(w, http.StatusNotFound, map[string]any{"error": "trigger_subscription_not_found"})
			return
		}
		writeBridge(w, http.StatusOK, value)
		return
	case "put", "disable":
	default:
		writeBridge(w, http.StatusBadRequest, map[string]any{"error": "unsupported_operation"})
		return
	}
	if input.ID == "" {
		writeBridge(w, http.StatusBadRequest, map[string]any{"error": "id_required"})
		return
	}
	var pendingSubscription triggers.Subscription
	if input.Operation == "put" {
		job, err := b.jobs.Get(r.Context(), jobsID(scope.JobID))
		if err != nil {
			writeBridge(w, http.StatusForbidden, map[string]any{"error": "execution_revoked"})
			return
		}
		interval := time.Duration(input.IntervalSeconds) * time.Second
		nextRun := time.Time{}
		if input.NextRun != "" {
			parsed, parseErr := time.Parse(time.RFC3339, input.NextRun)
			if parseErr != nil {
				writeBridge(w, http.StatusBadRequest, map[string]any{"error": "invalid_next_run"})
				return
			}
			nextRun = parsed.UTC()
		}
		enabled := true
		if input.Enabled != nil {
			enabled = *input.Enabled
		}
		rootThreadTS := input.RootThreadTS
		if rootThreadTS == "" {
			rootThreadTS = scope.ThreadTS
		}
		pendingSubscription = triggers.Subscription{ID: input.ID, OrganizationID: scope.OrganizationID, WorkspaceID: scope.WorkspaceID, ChannelID: scope.ChannelID, RootThreadTS: rootThreadTS, SessionID: job.SessionID, Generation: job.Generation, OwnerID: b.approvalRequester(r.Context(), scope), Kind: triggers.KindHeartbeat, Instruction: input.Instruction, Cron: input.Cron, Timezone: input.Timezone, Interval: interval, NextRun: nextRun, ClassifierGate: true, MinConfidence: input.MinConfidence, Enabled: enabled}
		pendingSubscription, err = triggers.Normalize(pendingSubscription, time.Now().UTC())
		if err != nil {
			writeBridge(w, http.StatusUnprocessableEntity, map[string]any{"error": "invalid_trigger_subscription"})
			return
		}
	}
	actionArguments := map[string]any{"id": input.ID, "instruction": input.Instruction, "cron": input.Cron, "timezone": input.Timezone, "interval_seconds": input.IntervalSeconds, "next_run": input.NextRun, "min_confidence": input.MinConfidence, "root_thread_ts": input.RootThreadTS}
	if input.Enabled != nil {
		actionArguments["enabled"] = *input.Enabled
	}
	action := approvals.Action{OrganizationID: scope.OrganizationID, JobID: scope.JobID, WorkspaceID: scope.WorkspaceID, ChannelID: scope.ChannelID, ThreadTS: scope.ThreadTS, ToolID: "tos-tag-triggers", ToolVersion: "v1", OperationID: input.Operation, Arguments: actionArguments, Destination: scope.WorkspaceID + "/" + scope.ChannelID, Risk: "write"}
	if input.ApprovalID == "" {
		requesterID := b.approvalRequester(r.Context(), scope)
		approval, err := b.approvals.RequestContext(r.Context(), action, requesterID, approvalTTL(scope))
		if err != nil {
			writeBridge(w, http.StatusInternalServerError, map[string]any{"error": "approval_unavailable"})
			return
		}
		actionBytes, _ := json.Marshal(action)
		if _, err := b.audit.Append(r.Context(), audit.AppendRequest{OrganizationID: scope.OrganizationID, Type: "trigger.approval.requested", ActorID: requesterID, ResourceID: approval.ID, RetentionEpoch: time.Now().UTC().Format("2006-01"), IdempotencyKey: "trigger-approval/" + approval.ID, Metadata: map[string]any{"operation_id": input.Operation, "trigger_id": input.ID, "channel_id": scope.ChannelID}, Content: actionBytes}); err != nil {
			writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "audit_unavailable"})
			return
		}
		if b.approvalCoordinator == nil || b.approvalCoordinator.SuspendAndNotify(r.Context(), approvals.RequestScope{JobID: jobsID(scope.JobID), LeaseToken: scope.LeaseToken, WorkspaceID: scope.WorkspaceID, ChannelID: scope.ChannelID, ThreadTS: scope.ThreadTS}, approval) != nil {
			writeBridge(w, http.StatusServiceUnavailable, map[string]any{"error": "approval_delivery_unavailable"})
			return
		}
		writeBridge(w, http.StatusConflict, map[string]any{"error": "approval_required", "approval_id": approval.ID, "expires_at": approval.ExpiresAt})
		return
	}
	if _, err := b.approvals.ConsumeContext(r.Context(), scope.OrganizationID, input.ApprovalID, action); err != nil {
		writeBridge(w, http.StatusForbidden, map[string]any{"error": "approval_invalid"})
		return
	}
	if input.Operation == "disable" {
		value, err := b.triggers.GetContext(r.Context(), scope.OrganizationID, scope.WorkspaceID, scope.ChannelID, input.ID)
		if err != nil {
			writeBridge(w, http.StatusNotFound, map[string]any{"error": "trigger_subscription_not_found"})
			return
		}
		value.Enabled = false
		saved, err := b.triggers.PutContext(r.Context(), value)
		if err != nil {
			writeBridge(w, http.StatusUnprocessableEntity, map[string]any{"error": "invalid_trigger_subscription"})
			return
		}
		writeBridge(w, http.StatusOK, saved)
		return
	}
	saved, err := b.triggers.PutContext(r.Context(), pendingSubscription)
	if err != nil {
		if errors.Is(err, triggers.ErrScopeConflict) {
			writeBridge(w, http.StatusForbidden, map[string]any{"error": "trigger_subscription_scope_denied"})
			return
		}
		writeBridge(w, http.StatusUnprocessableEntity, map[string]any{"error": "invalid_trigger_subscription"})
		return
	}
	_, _ = b.audit.Append(r.Context(), audit.AppendRequest{OrganizationID: scope.OrganizationID, Type: "trigger.subscription.put", ActorID: "agent:" + scope.JobID, ResourceID: saved.ChannelID + "/" + saved.ID, RetentionEpoch: time.Now().UTC().Format("2006-01"), IdempotencyKey: "trigger-subscription/" + saved.ChannelID + "/" + saved.ID + "/" + fmt.Sprint(saved.Version), Metadata: map[string]any{"channel_id": saved.ChannelID, "enabled": saved.Enabled, "version": saved.Version}})
	writeBridge(w, http.StatusOK, saved)
}

func containsTool(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func (b *Bridge) approvalRequester(_ context.Context, scope JobScope) string {
	// The executing agent is the requester of the concrete tool action. The
	// human who asked for the higher-level Slack task must remain eligible to
	// approve the exact immutable action the agent subsequently proposed.
	return "agent:" + scope.JobID
}

func (b *Bridge) authorize(ctx context.Context, scope JobScope) error {
	if !scope.ExpiresAt.After(time.Now().UTC()) {
		return errors.New("scope expired")
	}
	job, err := b.jobs.Get(ctx, jobsID(scope.JobID))
	if err != nil || job.OrganizationID != scope.OrganizationID || job.State != jobs.StateRunning || job.SteeringEpoch != scope.SteeringEpoch || job.Lease.Token != scope.LeaseToken || !job.Lease.ExpiresAt.After(time.Now().UTC()) {
		return errors.New("job lease no longer authorizes tools")
	}
	return nil
}

func jobsID(value string) types.JobID { return types.JobID(value) }

func approvalTTL(scope JobScope) time.Duration {
	ttl := 30 * time.Minute
	if remaining := time.Until(scope.ExpiresAt); remaining > 0 && remaining < ttl {
		ttl = remaining
	}
	return ttl
}

func randomCapability() (string, error) {
	value := make([]byte, 32)
	if _, err := rand.Read(value); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(value), nil
}

func writeBridge(w http.ResponseWriter, status int, value any) {
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(value)
}

func minTime(a, c time.Time) time.Time {
	if a.Before(c) {
		return a
	}
	return c
}

var _ interface {
	RevokeAttempt(context.Context, string) error
} = (*Bridge)(nil)
